name = "ACM UMN Theme"
description = ""
license = "MIT"
homepage = "https://acm.umn.edu"
min_version = "0.3"

[extra]
nav_links = [
    { url = "/about", text = "Home" }
]

[author]
name = "ACM UMN"
homepage = "https://acm.umn.edu"

